//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package com.example;

import java.util.concurrent.CompletableFuture;
import com.example.parsec_generated.ResourceException;
import com.example.parsec_generated.User;


public interface SampleClient {

    CompletableFuture<User> getUser(int id) throws ResourceException;
    CompletableFuture<String> postUser(User user) throws ResourceException;
    CompletableFuture<String> putUser(int id, User user) throws ResourceException;
}
